// Generated by PinPilot. Source: project.json
// Purpose: Driver header for BH1750 ambient light sensor (bh1750_1)
// Do not edit manually — regenerate from project.json.

#pragma once

#include <Arduino.h>
#include <Wire.h>
#include <BH1750.h>

class BH1750_1 {
public:
    BH1750_1() = default;

    bool  begin();
    void  update();

    float getLight() const { return _lux; }

private:
    BH1750   _lightMeter;
    float    _lux      = 0.0f;
    uint32_t _lastRead = 0;
    bool     _ready    = false;
};

extern BH1750_1 bh1750_1;
