// Generated by PinPilot. Source: project.json
// Purpose: Driver implementation for BH1750 ambient light sensor (bh1750_1)
// Do not edit manually — regenerate from project.json.

#include "bh1750_1.h"
#include "pinmap.h"

static const uint32_t MIN_INTERVAL_MS = 180;

BH1750_1 bh1750_1;

bool BH1750_1::begin() {
    if (!_lightMeter.begin(BH1750::CONTINUOUS_HIGH_RES_MODE, ADDR_BH1750_1, &Wire)) {
        Serial.println("[bh1750_1] ERROR: BH1750 not found at address ADDR_BH1750_1. Check wiring and I2C address.");
        _ready = false;
        return false;
    }
    _ready = true;
    Serial.println("[bh1750_1] BH1750 initialised OK.");
    return true;
}

void BH1750_1::update() {
    if (!_ready) return;
    if (millis() - _lastRead < MIN_INTERVAL_MS) return;

    _lastRead = millis();
    _lux      = _lightMeter.readLightLevel();
}
