// Generated by PinPilot. Source: project.json
// Purpose: Driver implementation for BME280 temperature/humidity/pressure sensor (bme280_1)
// Do not edit manually — regenerate from project.json.

#include "bme280_1.h"
#include "pinmap.h"

static const uint32_t MIN_INTERVAL_MS = 1000;

BME280_1 bme280_1;

bool BME280_1::begin() {
    if (!_bme.begin(ADDR_BME280_1, &Wire)) {
        Serial.println("[bme280_1] ERROR: BME280 not found at address ADDR_BME280_1. Check wiring and I2C address.");
        _ready = false;
        return false;
    }
    _ready = true;
    Serial.println("[bme280_1] BME280 initialised OK.");
    return true;
}

void BME280_1::update() {
    if (!_ready) return;
    if (millis() - _lastRead < MIN_INTERVAL_MS) return;

    _lastRead    = millis();
    _temperature = _bme.readTemperature();
    _humidity    = _bme.readHumidity();
    _pressure    = _bme.readPressure() / 100.0f;   // Pa -> hPa
}
