// Generated by PinPilot. Source: project.json
// Purpose: Driver header for BME280 temperature/humidity/pressure sensor (bme280_1)
// Do not edit manually — regenerate from project.json.

#pragma once

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_BME280.h>

class BME280_1 {
public:
    BME280_1() = default;

    bool  begin();
    void  update();

    float getTemperature() const { return _temperature; }
    float getHumidity()    const { return _humidity; }
    float getPressure()    const { return _pressure; }

private:
    Adafruit_BME280 _bme;
    float           _temperature = 0.0f;
    float           _humidity    = 0.0f;
    float           _pressure    = 0.0f;
    uint32_t        _lastRead    = 0;
    bool            _ready       = false;
};

extern BME280_1 bme280_1;
