// Generated by PinPilot. Source: project.json
// Purpose: SSD1306 128x64 OLED display driver implementation using U8g2 (I2C, hardware bus).
// Do not edit manually — regenerate from project.json.

#include "display.h"
#include "pinmap.h"   // ADDR_SSD1306_1, I2C_SCL, I2C_SDA

#include <Arduino.h>  // Serial
#include <stdio.h>    // snprintf

// ---------------------------------------------------------------------------
// Constructor
// U8G2_R0 = no rotation. U8X8_PIN_NONE = no reset pin wired.
// I2C address and bus pins come from pinmap.h constants.
// ---------------------------------------------------------------------------
Display::Display()
    : u8g2_(U8G2_R0,
            /* reset */ U8X8_PIN_NONE,
            /* clock */ I2C_SCL,
            /* data  */ I2C_SDA)
{}

// ---------------------------------------------------------------------------
// begin()
// ---------------------------------------------------------------------------
bool Display::begin() {
    // The hardware I2C constructor picks up ADDR_SSD1306_1 automatically via
    // the Wire address scan that U8g2 performs; no explicit address call needed.
    // The address used: ADDR_SSD1306_1 = 0x3C (from pinmap.h).
    (void)ADDR_SSD1306_1;  // ensure linker keeps the symbol, documents intent

    if (!u8g2_.begin()) {
        Serial.println("[Display] ERROR: u8g2.begin() failed - check wiring and I2C address.");
        return false;
    }
    Serial.println("[Display] SSD1306 OLED initialised OK.");
    return true;
}

// ---------------------------------------------------------------------------
// update()
// Draws three sensor label lines and pushes the full buffer to the display.
// Non-blocking — no delay() calls.
//
// Widget layout (from project.json screen block):
//   id=temp_label   binding=bme280_1.temperature  label="Temp"  unit="degC" x=0 y=0
//   id=hum_label    binding=bme280_1.humidity      label="Hum"   unit="%"    x=0 y=16
//   id=light_label  binding=bh1750_1.light         label="Light" unit="lux"  x=0 y=32
//
// Font: u8g2_font_6x10_tf (~10 px tall) — fits all 3 lines inside 64 px height.
// U8g2 y is the text baseline; add 10 px offset so the top of the glyph sits at
// the widget's logical y coordinate.
// ---------------------------------------------------------------------------
void Display::update(float temp, float hum, float light) {
    char buf[32];

    u8g2_.clearBuffer();
    u8g2_.setFont(u8g2_font_6x10_tf);

    // Widget 1 — id: temp_label  |  Temp: 24.5 C  |  x=0, y=0
    snprintf(buf, sizeof(buf), "Temp: %.1f C", temp);
    u8g2_.setCursor(0, 0 + 10);
    u8g2_.print(buf);

    // Widget 2 — id: hum_label   |  Hum: 55.2 %   |  x=0, y=16
    snprintf(buf, sizeof(buf), "Hum: %.1f %%", hum);
    u8g2_.setCursor(0, 16 + 10);
    u8g2_.print(buf);

    // Widget 3 — id: light_label |  Light: 320 lux |  x=0, y=32
    snprintf(buf, sizeof(buf), "Light: %.0f lux", light);
    u8g2_.setCursor(0, 32 + 10);
    u8g2_.print(buf);

    u8g2_.sendBuffer();
}
