// Generated by PinPilot. Source: project.json
// Purpose: SSD1306 128x64 OLED display driver using U8g2 (I2C, hardware bus).
// Do not edit manually — regenerate from project.json.

#pragma once

#include <U8g2lib.h>
#include <Wire.h>

class Display {
public:
    Display();

    /**
     * Initialise U8g2 and the SSD1306 over hardware I2C.
     * Returns false if u8g2.begin() fails.
     * // If using a 1.3-inch OLED, try U8G2_SH1106_128X64_NONAME_F_HW_I2C instead.
     */
    bool begin();

    /**
     * Clear the buffer, draw all sensor widgets, and push to the display.
     * Non-blocking — no delay() calls.
     *
     * @param temp   Temperature reading from bme280_1.temperature  (degC)
     * @param hum    Humidity reading    from bme280_1.humidity      (%)
     * @param light  Light reading       from bh1750_1.light         (lux)
     */
    void update(float temp, float hum, float light);

private:
    // Full-buffer hardware-I2C constructor.
    // If using a 1.3-inch OLED, try U8G2_SH1106_128X64_NONAME_F_HW_I2C instead.
    U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2_;
};
