// Generated by PinPilot. Source: project.json
// Purpose: LVGL v9 configuration for smart_farm_node (ILI9341, widgets: arc, label, chart)
// Do not edit manually — regenerate from project.json.
#if defined(LV_CONF_INCLUDE_SIMPLE)

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

/*====================
   COLOR SETTINGS
 *====================*/
/* Color depth: 16 (RGB565) for TFT displays */
#define LV_COLOR_DEPTH 16

/*====================
   MEMORY SETTINGS
 *====================*/
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (48U * 1024U)  /* 48 KB LVGL heap */

/*====================
   HAL SETTINGS
 *====================*/
#define LV_TICK_CUSTOM 1  /* Use lv_tick_set_cb(millis) */

/*====================
   LOGGING
 *====================*/
#define LV_USE_LOG 0

/*====================
   ASSERT
 *====================*/
#define LV_USE_ASSERT_NULL          1
#define LV_USE_ASSERT_MALLOC        1
#define LV_USE_ASSERT_STYLE         0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ           0

/*====================
   FONTS
 *====================*/
/* Only enable the Montserrat font sizes actually used */
#define LV_FONT_MONTSERRAT_12  1
#define LV_FONT_MONTSERRAT_14  1
#define LV_FONT_DEFAULT        &lv_font_montserrat_14

/* Disable all other built-in fonts to save flash */
#define LV_FONT_MONTSERRAT_8   0
#define LV_FONT_MONTSERRAT_10  0
#define LV_FONT_MONTSERRAT_16  0
#define LV_FONT_MONTSERRAT_18  0
#define LV_FONT_MONTSERRAT_20  0
#define LV_FONT_MONTSERRAT_22  0
#define LV_FONT_MONTSERRAT_24  0
#define LV_FONT_MONTSERRAT_26  0
#define LV_FONT_MONTSERRAT_28  0
#define LV_FONT_MONTSERRAT_30  0
#define LV_FONT_MONTSERRAT_32  0
#define LV_FONT_MONTSERRAT_34  0
#define LV_FONT_MONTSERRAT_36  0
#define LV_FONT_MONTSERRAT_38  0
#define LV_FONT_MONTSERRAT_40  0
#define LV_FONT_MONTSERRAT_42  0
#define LV_FONT_MONTSERRAT_44  0
#define LV_FONT_MONTSERRAT_46  0
#define LV_FONT_MONTSERRAT_48  0
#define LV_FONT_UNSCII_8       0
#define LV_FONT_UNSCII_16      0

/*====================
   WIDGET ENABLE
 *====================*/
/* Enable only what is used by this project */
#define LV_USE_ARC      1   /* moisture_arc */
#define LV_USE_LABEL    1   /* temp_label, soil_temp_label, value labels */
#define LV_USE_CHART    1   /* moisture_chart */

/* Disable all unused widgets */
#define LV_USE_ANIMIMG       0
#define LV_USE_BAR           0
#define LV_USE_BTN           0
#define LV_USE_BTNMATRIX     0
#define LV_USE_CALENDAR      0
#define LV_USE_CANVAS        0
#define LV_USE_CHECKBOX      0
#define LV_USE_DROPDOWN      0
#define LV_USE_IMG           0
#define LV_USE_IMGBTN        0
#define LV_USE_KEYBOARD      0
#define LV_USE_LED           0
#define LV_USE_LINE          0
#define LV_USE_LIST          0
#define LV_USE_MENU          0
#define LV_USE_METER         0
#define LV_USE_MSGBOX        0
#define LV_USE_ROLLER        0
#define LV_USE_SCALE         0
#define LV_USE_SLIDER        0
#define LV_USE_SPAN          0
#define LV_USE_SPINBOX       0
#define LV_USE_SPINNER       0
#define LV_USE_SWITCH        0
#define LV_USE_TABLE         0
#define LV_USE_TABVIEW       0
#define LV_USE_TEXTAREA      0
#define LV_USE_TILEVIEW      0
#define LV_USE_WIN           0

/*====================
   TFT_eSPI DRIVER
 *====================*/
#define LV_USE_TFT_ESPI 1

#endif  /* LV_CONF_H */
#endif  /* LV_CONF_INCLUDE_SIMPLE */
