// Generated by PinPilot. Source: project.json
// Purpose: GPIO pin assignments and bus constants for smart_farm_node
// Do not edit manually — regenerate from project.json.
#pragma once

// ─── I2C Bus (i2c0) ────────────────────────────────────────────────────────
#define I2C_SDA_PIN           21
#define I2C_SCL_PIN           22
#define I2C_FREQ              400000

// ─── SPI Bus (spi0) ────────────────────────────────────────────────────────
#define SPI_MOSI_PIN          23
#define SPI_MISO_PIN          19
#define SPI_SCK_PIN           18
#define SPI_FREQ              40000000

// ─── soil_1 — Capacitive Soil Moisture Sensor v1.2 ─────────────────────────
// ADC1 pin — safe with WiFi
#define PIN_SOIL_1_AOUT       34

// ─── ds18b20_1 — DS18B20 1-Wire Temperature Sensor ──────────────────────────
#define PIN_DS18B20_1_DQ      4

// ─── bme280_1 — BME280 Temperature/Humidity/Pressure (I2C) ─────────────────
#define PIN_BME280_1_SDA      21
#define PIN_BME280_1_SCL      22
#define ADDR_BME280_1         0x76    // i2c_address=118 decimal; SDO→GND

// ─── relay_1 — Single-Channel Relay Module (active LOW) ─────────────────────
// GPIO 26 is ADC2 — only used as digital output here (no ADC read), safe
#define PIN_RELAY_1_IN        26

// ─── ili9341_1 — ILI9341 2.8" TFT Display (SPI) ────────────────────────────
#define PIN_ILI9341_1_MOSI    23
#define PIN_ILI9341_1_MISO    19
#define PIN_ILI9341_1_SCK     18
#define PIN_ILI9341_1_CS      27
#define PIN_ILI9341_1_DC      16
#define PIN_ILI9341_1_RESET   17
