// Generated by PinPilot. Source: project.json
// Purpose: BME280 temperature/humidity/pressure sensor driver implementation
// Do not edit manually — regenerate from project.json.
#include "bme280_1.h"
#include "pinmap.h"

bool Bme280_1::begin() {
    if (!_bme.begin(ADDR_BME280_1)) {
        Serial.println("[bme280_1] ERROR: BME280 not found at I2C address 0x" + String(ADDR_BME280_1, HEX));
        return false;
    }
    Serial.println("[bme280_1] BME280 initialised at I2C address 0x" + String(ADDR_BME280_1, HEX));
    return true;
}

void Bme280_1::update() {
    if (millis() - _lastRead < 1000) return;
    _lastRead = millis();
    _temperature = _bme.readTemperature();
    _humidity    = _bme.readHumidity();
    _pressure    = _bme.readPressure() / 100.0f;
}
