// Generated by PinPilot. Source: project.json
// Purpose: ILI9341 TFT display driver and LVGL GUI header
// Do not edit manually — regenerate from project.json.
#pragma once
#include <Arduino.h>
#include <lvgl.h>

class Display {
public:
    bool begin();
    void update(float moisture, float airTemp, float soilTemp);
    void tick();  // call every ~5ms from main loop
private:
    lv_obj_t* _arcMoisture    = nullptr;
    lv_obj_t* _lblArcVal      = nullptr;
    lv_obj_t* _lblAirTemp     = nullptr;
    lv_obj_t* _lblSoilTemp    = nullptr;
    lv_obj_t* _chart          = nullptr;
    lv_chart_series_t* _chartSeries = nullptr;

    // Track last values to avoid redundant redraws
    float _lastMoisture = -1.0f;
    float _lastAirTemp  = -1000.0f;
    float _lastSoilTemp = -1000.0f;

    void _buildUI();
};

extern Display displayDriver;
