// Generated by PinPilot. Source: project.json
// Purpose: ILI9341 TFT display driver and LVGL GUI implementation
// Do not edit manually — regenerate from project.json.
#include "display.h"
#include "pinmap.h"

Display displayDriver;

// LVGL v9 tick callback — must return uint32_t, millis() returns unsigned long
static uint32_t lvgl_tick_cb() { return (uint32_t)millis(); }

// Partial draw buffer — 320×24 pixels × 2 bytes = 15 360 bytes (~15 KB)
static lv_color_t _lvBuf[320 * 24];

bool Display::begin() {
    // 1. Init LVGL
    lv_init();

    // 2. Provide tick source — LVGL v9 API (wrapper to match uint32_t return type)
    lv_tick_set_cb(lvgl_tick_cb);

    // 3. Create display using the built-in TFT_eSPI driver (LVGL v9)
    //    Pins are configured via build_flags (USER_SETUP_LOADED, ILI9341_DRIVER, TFT_* defines)
    lv_display_t* disp = lv_tft_espi_create(320, 240, _lvBuf, sizeof(_lvBuf));
    if (disp == nullptr) {
        Serial.println("[display] ERROR: lv_tft_espi_create returned nullptr");
        return false;
    }

    Serial.println("[display] ILI9341 LVGL display initialised (320x240, partial buffer 15KB)");

    // 4. Build the UI
    _buildUI();
    return true;
}

void Display::_buildUI() {
    lv_obj_t* scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_black(), LV_PART_MAIN);

    // --- moisture_arc: Arc widget at (10, 40), 100x100, range 0-100 ---
    _arcMoisture = lv_arc_create(scr);
    lv_obj_set_pos(_arcMoisture, 10, 40);
    lv_obj_set_size(_arcMoisture, 100, 100);
    lv_arc_set_range(_arcMoisture, 0, 100);
    lv_arc_set_value(_arcMoisture, 0);
    lv_arc_set_bg_angles(_arcMoisture, 135, 45);  // 270° sweep
    lv_obj_remove_style(_arcMoisture, NULL, LV_PART_KNOB);  // hide knob (display only)
    lv_obj_clear_flag(_arcMoisture, LV_OBJ_FLAG_CLICKABLE);

    // Label for arc value
    _lblArcVal = lv_label_create(scr);
    lv_obj_set_pos(_lblArcVal, 40, 80);
    lv_label_set_text(_lblArcVal, "0%");
    lv_obj_set_style_text_color(_lblArcVal, lv_color_white(), LV_PART_MAIN);

    // Header label for arc
    lv_obj_t* lblArcTitle = lv_label_create(scr);
    lv_obj_set_pos(lblArcTitle, 15, 145);
    lv_label_set_text(lblArcTitle, "Moisture");
    lv_obj_set_style_text_color(lblArcTitle, lv_color_make(0xAA, 0xAA, 0xAA), LV_PART_MAIN);

    // --- temp_label: Air temperature at (160, 20) ---
    lv_obj_t* lblTempTitle = lv_label_create(scr);
    lv_obj_set_pos(lblTempTitle, 160, 20);
    lv_label_set_text(lblTempTitle, "Temp");
    lv_obj_set_style_text_color(lblTempTitle, lv_color_make(0xAA, 0xAA, 0xAA), LV_PART_MAIN);

    _lblAirTemp = lv_label_create(scr);
    lv_obj_set_pos(_lblAirTemp, 160, 38);
    lv_label_set_text(_lblAirTemp, "--.-C");
    lv_obj_set_style_text_color(_lblAirTemp, lv_color_white(), LV_PART_MAIN);

    // --- soil_temp_label: Soil temperature at (160, 80) ---
    lv_obj_t* lblSoilTempTitle = lv_label_create(scr);
    lv_obj_set_pos(lblSoilTempTitle, 160, 80);
    lv_label_set_text(lblSoilTempTitle, "Soil T");
    lv_obj_set_style_text_color(lblSoilTempTitle, lv_color_make(0xAA, 0xAA, 0xAA), LV_PART_MAIN);

    _lblSoilTemp = lv_label_create(scr);
    lv_obj_set_pos(_lblSoilTemp, 160, 98);
    lv_label_set_text(_lblSoilTemp, "--.-C");
    lv_obj_set_style_text_color(_lblSoilTemp, lv_color_white(), LV_PART_MAIN);

    // --- moisture_chart: Chart at (0, 160), 320x70 ---
    _chart = lv_chart_create(scr);
    lv_obj_set_pos(_chart, 0, 160);
    lv_obj_set_size(_chart, 320, 70);
    lv_chart_set_type(_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
    lv_chart_set_point_count(_chart, 60);
    lv_obj_set_style_bg_color(_chart, lv_color_make(0x11, 0x11, 0x11), LV_PART_MAIN);
    lv_obj_set_style_border_width(_chart, 0, LV_PART_MAIN);

    _chartSeries = lv_chart_add_series(_chart, lv_palette_main(LV_PALETTE_GREEN), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_all_value(_chart, _chartSeries, LV_CHART_POINT_NONE);

    lv_obj_t* lblChartTitle = lv_label_create(scr);
    lv_obj_set_pos(lblChartTitle, 4, 162);
    lv_label_set_text(lblChartTitle, "Moisture history");
    lv_obj_set_style_text_color(lblChartTitle, lv_color_make(0xAA, 0xAA, 0xAA), LV_PART_MAIN);
}

void Display::update(float moisture, float airTemp, float soilTemp) {
    bool dirty = false;

    if (moisture != _lastMoisture) {
        _lastMoisture = moisture;
        lv_arc_set_value(_arcMoisture, (int)moisture);
        char buf[12];
        snprintf(buf, sizeof(buf), "%d%%", (int)moisture);
        lv_label_set_text(_lblArcVal, buf);
        lv_chart_set_next_value(_chart, _chartSeries, (int)moisture);
        dirty = true;
    }

    if (airTemp != _lastAirTemp) {
        _lastAirTemp = airTemp;
        char buf[16];
        snprintf(buf, sizeof(buf), "%.1fC", airTemp);
        lv_label_set_text(_lblAirTemp, buf);
        dirty = true;
    }

    if (soilTemp != _lastSoilTemp) {
        _lastSoilTemp = soilTemp;
        char buf[16];
        snprintf(buf, sizeof(buf), "%.1fC", soilTemp);
        lv_label_set_text(_lblSoilTemp, buf);
        dirty = true;
    }

    (void)dirty;
}

void Display::tick() {
    lv_timer_handler();
}
