// Generated by PinPilot. Source: project.json
// Purpose: DS18B20 1-Wire temperature sensor driver header
// Do not edit manually — regenerate from project.json.
#pragma once
#include <Arduino.h>
#include <OneWire.h>
#include <DallasTemperature.h>

class Ds18b20_1 {
public:
    Ds18b20_1();
    bool begin();
    void update();
    float getTemperature() const { return _temperature; }
private:
    OneWire _ow;
    DallasTemperature _dt;
    float _temperature = -127.0f;
    uint32_t _lastRequest = 0;
    bool _conversionPending = false;
};
