// Generated by PinPilot. Source: project.json
// Purpose: DS18B20 1-Wire temperature sensor driver implementation
// Do not edit manually — regenerate from project.json.
#include "ds18b20_1.h"
#include "pinmap.h"

Ds18b20_1::Ds18b20_1() : _ow(PIN_DS18B20_1_DQ), _dt(&_ow) {}

bool Ds18b20_1::begin() {
    _dt.begin();
    uint8_t count = _dt.getDeviceCount();
    if (count == 0) {
        Serial.println("[ds18b20_1] ERROR: No DS18B20 devices found on GPIO " + String(PIN_DS18B20_1_DQ));
        return false;
    }
    Serial.println("[ds18b20_1] Found " + String(count) + " DS18B20 device(s) on GPIO " + String(PIN_DS18B20_1_DQ));
    _dt.setResolution(12);
    _dt.setWaitForConversion(false);
    _dt.requestTemperatures();
    _lastRequest = millis();
    _conversionPending = true;
    return true;
}

void Ds18b20_1::update() {
    if (_conversionPending) {
        if (millis() - _lastRequest >= 750) {
            _temperature = _dt.getTempCByIndex(0);
            _conversionPending = false;
        }
    } else {
        if (millis() - _lastRequest >= 750) {
            _dt.requestTemperatures();
            _lastRequest = millis();
            _conversionPending = true;
        }
    }
}
