// Generated by PinPilot. Source: project.json
// Purpose: Single-channel relay module driver header (active LOW)
// Do not edit manually — regenerate from project.json.
#pragma once
#include <Arduino.h>

class Relay1 {
public:
    bool begin();
    void setOn(bool on);
    bool isOn() const { return _on; }
    void update() {}   // No periodic action needed
private:
    bool _on = false;
};
