// Generated by PinPilot. Source: project.json
// Purpose: Single-channel relay module driver implementation (active LOW)
// Do not edit manually — regenerate from project.json.
#include "relay_1.h"
#include "pinmap.h"

bool Relay1::begin() {
    // Write HIGH first (deactivate relay) BEFORE setting OUTPUT to prevent boot click
    digitalWrite(PIN_RELAY_1_IN, HIGH);
    pinMode(PIN_RELAY_1_IN, OUTPUT);
    digitalWrite(PIN_RELAY_1_IN, HIGH); // ensure deactivated
    Serial.println("[relay_1] Relay initialised on GPIO " + String(PIN_RELAY_1_IN) + " (active LOW, currently OFF)");
    return true;
}

void Relay1::setOn(bool on) {
    _on = on;
    // Active LOW: HIGH = relay OFF, LOW = relay ON
    digitalWrite(PIN_RELAY_1_IN, on ? LOW : HIGH);
}
