// Generated by PinPilot. Source: project.json
// Purpose: Capacitive soil moisture sensor v1.2 driver header
// Do not edit manually — regenerate from project.json.
#pragma once
#include <Arduino.h>

class Soil1 {
public:
    bool begin();
    void update();
    float getMoisture() const { return _moisture; }
private:
    float _moisture = 0.0f;
    uint32_t _lastRead = 0;
};
