// Generated by PinPilot. Source: project.json
// Purpose: Capacitive soil moisture sensor v1.2 driver implementation
// Do not edit manually — regenerate from project.json.
#include "soil_1.h"
#include "pinmap.h"

bool Soil1::begin() {
    pinMode(PIN_SOIL_1_AOUT, INPUT);
    Serial.println("[soil_1] Capacitive soil moisture sensor initialised on GPIO " + String(PIN_SOIL_1_AOUT));
    return true;
}

void Soil1::update() {
    if (millis() - _lastRead < 500) return;
    _lastRead = millis();
    int raw = analogRead(PIN_SOIL_1_AOUT);
    // Capacitive sensor: high ADC = dry, low ADC = wet. Typical range: 1500 (wet) - 2900 (dry)
    float m = (float)(2900 - raw) / (2900 - 1500) * 100.0f;
    if (m < 0.0f)   m = 0.0f;
    if (m > 100.0f) m = 100.0f;
    _moisture = m;
}
