// Generated by PinPilot. Source: project.json
// Purpose: Main entry point for smart_farm_node firmware
// Do not edit manually — regenerate from project.json.

#include <Arduino.h>
#include <Wire.h>

#include "pinmap.h"
#include "components/soil_1.h"
#include "components/ds18b20_1.h"
#include "components/bme280_1.h"
#include "components/relay_1.h"
#include "components/display.h"

// ─── Component instances ────────────────────────────────────────────────────
Soil1     soil1;
Ds18b20_1 ds18b20_1;
Bme280_1  bme280_1;
Relay1    relay1;
// displayDriver is defined as extern in display.h / defined in display.cpp

// ─── Timing ─────────────────────────────────────────────────────────────────
static uint32_t _lastDisplayUpdate = 0;
static uint32_t _lastLvglTick      = 0;

// ─── Setup ──────────────────────────────────────────────────────────────────
void setup() {
    Serial.begin(115200);
    delay(100);  // brief stabilisation — only in setup(), never in loop()

    Serial.println("==============================================");
    Serial.println("  PinPilot Firmware — smart_farm_node");
    Serial.println("  Source: project.json");
    Serial.println("==============================================");

    // Bus configuration summary
    Serial.println("[bus] I2C  — SDA=" + String(I2C_SDA_PIN) +
                   "  SCL=" + String(I2C_SCL_PIN) +
                   "  freq=" + String(I2C_FREQ / 1000) + " kHz");
    Serial.println("[bus] SPI  — MOSI=" + String(SPI_MOSI_PIN) +
                   "  MISO=" + String(SPI_MISO_PIN) +
                   "  SCK="  + String(SPI_SCK_PIN) +
                   "  freq=" + String(SPI_FREQ / 1000000) + " MHz");

    // Pin map summary
    Serial.println("[pinmap] soil_1.AOUT    = GPIO " + String(PIN_SOIL_1_AOUT));
    Serial.println("[pinmap] ds18b20_1.DQ   = GPIO " + String(PIN_DS18B20_1_DQ));
    Serial.println("[pinmap] bme280_1 I2C   = 0x" + String(ADDR_BME280_1, HEX));
    Serial.println("[pinmap] relay_1.IN     = GPIO " + String(PIN_RELAY_1_IN));
    Serial.println("[pinmap] ili9341_1.CS   = GPIO " + String(PIN_ILI9341_1_CS));
    Serial.println("[pinmap] ili9341_1.DC   = GPIO " + String(PIN_ILI9341_1_DC));
    Serial.println("[pinmap] ili9341_1.RST  = GPIO " + String(PIN_ILI9341_1_RESET));

    // Initialise shared I2C bus — must be called ONCE before any I2C device begin()
    Wire.begin(I2C_SDA_PIN, I2C_SCL_PIN);
    Wire.setClock(I2C_FREQ);
    Serial.println("[i2c] Wire.begin() done");

    // Initialise all components
    bool ok_soil    = soil1.begin();
    bool ok_ds      = ds18b20_1.begin();
    bool ok_bme     = bme280_1.begin();
    bool ok_relay   = relay1.begin();
    bool ok_display = displayDriver.begin();

    // Startup device summary
    Serial.println("----------------------------------------------");
    Serial.println("[init] soil_1      : " + String(ok_soil    ? "OK" : "NOT FOUND"));
    Serial.println("[init] ds18b20_1   : " + String(ok_ds      ? "OK" : "NOT FOUND"));
    Serial.println("[init] bme280_1    : " + String(ok_bme     ? "OK" : "NOT FOUND"));
    Serial.println("[init] relay_1     : " + String(ok_relay   ? "OK" : "NOT FOUND"));
    Serial.println("[init] ili9341_1   : " + String(ok_display ? "OK" : "NOT FOUND"));
    Serial.println("==============================================");
}

// ─── Loop ───────────────────────────────────────────────────────────────────
// Non-blocking: no delay() calls anywhere.
// Each sensor polls on its own millis() interval.
// LVGL tick handler runs every ~5 ms.
// Display update runs when any sensor delivers fresh data.
void loop() {
    uint32_t now = millis();

    // Update all sensor/actuator drivers (each enforces its own read interval internally)
    soil1.update();
    ds18b20_1.update();
    bme280_1.update();
    relay1.update();

    // Run LVGL timer handler every ~5 ms (must not block)
    if (now - _lastLvglTick >= 5) {
        _lastLvglTick = now;
        displayDriver.tick();
    }

    // Refresh display widgets once per second with latest sensor values
    if (now - _lastDisplayUpdate >= 1000) {
        _lastDisplayUpdate = now;
        displayDriver.update(
            soil1.getMoisture(),
            bme280_1.getTemperature(),
            ds18b20_1.getTemperature()
        );
    }
}
