"""
build.py — PinPilot PlatformIO build wrapper.
Generated by PinPilot. Source: docs/PROJECT_PINPILOT.md §14.2.
Usage: python scripts/build.py <firmware_directory>
Exit code: 0 = BUILD PASSED, 1 = BUILD FAILED, 2 = bad arguments.
Prints BUILD PASSED or BUILD FAILED, plus the first error lines on failure.
"""

import argparse
import subprocess
import sys
from pathlib import Path

MAX_ERROR_LINES = 20  # Maximum number of error lines to print on failure


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run 'pio run' on a PlatformIO firmware directory and report the result."
    )
    parser.add_argument(
        "firmware_dir",
        type=Path,
        help="Path to the PlatformIO project directory (must contain platformio.ini)."
    )
    args = parser.parse_args()

    fw_dir: Path = args.firmware_dir

    if not fw_dir.exists():
        print(f"ERROR: Directory not found: {fw_dir}", file=sys.stderr)
        sys.exit(2)

    if not (fw_dir / "platformio.ini").exists():
        print(f"ERROR: No platformio.ini found in {fw_dir}", file=sys.stderr)
        sys.exit(2)

    print(f"Building: {fw_dir}")
    print()

    result = subprocess.run(
        ["pio", "run", "-d", str(fw_dir)],
        capture_output=True,
        text=True
    )

    combined_output = result.stdout + result.stderr

    if result.returncode == 0:
        # Extract RAM/flash usage summary from PlatformIO output
        usage_lines = [
            line for line in combined_output.splitlines()
            if "RAM:" in line or "Flash:" in line or "DATA:" in line or "PROGRAM:" in line
        ]
        if usage_lines:
            print("Memory usage:")
            for line in usage_lines:
                print(f"  {line.strip()}")
            print()
        print("BUILD PASSED")
        sys.exit(0)
    else:
        # Collect first error/fatal-error lines
        error_lines = []
        for line in combined_output.splitlines():
            lower = line.lower()
            if "error:" in lower or "fatal error:" in lower:
                error_lines.append(line.rstrip())
                if len(error_lines) >= MAX_ERROR_LINES:
                    break

        if error_lines:
            print(f"First {len(error_lines)} error line(s):")
            for line in error_lines:
                print(f"  {line}")
            print()

        print("BUILD FAILED")
        sys.exit(1)


if __name__ == "__main__":
    main()
