#!/usr/bin/env python3
"""
PinPilot — LaTeX documentation generator.
Generated by PinPilot. Source: project.json
Usage: python scripts/generate_docs.py <project.json> <output.tex>
"""

import json
import sys
from datetime import date
from pathlib import Path

CATALOG_DIR = Path(__file__).parent.parent / "catalog" / "components"
PIN_TABLE   = Path(__file__).parent.parent / "catalog" / "esp32_devkit_pins.json"


# ---------------------------------------------------------------------------
# LaTeX escaping — MUST be applied to all project-derived strings
# ---------------------------------------------------------------------------
def latex_escape(s: str) -> str:
    s = str(s)
    s = s.replace("\\", "\\textbackslash{}")
    s = s.replace("&",  "\\&")
    s = s.replace("%",  "\\%")
    s = s.replace("$",  "\\$")
    s = s.replace("#",  "\\#")
    s = s.replace("_",  "\\_")
    s = s.replace("{",  "\\{")
    s = s.replace("}",  "\\}")
    s = s.replace("^",  "\\^{}")
    s = s.replace("~",  "\\~{}")
    # Replace common Unicode characters not supported by pdflatex without inputenc
    s = s.replace("\u00b0", "\\textdegree{}")   # °
    s = s.replace("\u03a9", "\\ensuremath{\\Omega}")  # Ω
    s = s.replace("\u03bc", "\\ensuremath{\\mu}")     # μ
    s = s.replace("\u00b5", "\\ensuremath{\\mu}")     # µ (micro sign)
    s = s.replace("\u00d7", "\\texttimes{}")    # ×
    s = s.replace("\u2014", "---")              # em dash
    s = s.replace("\u2013", "--")               # en dash
    s = s.replace("\u2019", "'")                # right single quote
    s = s.replace("\u201c", "``")               # left double quote
    s = s.replace("\u201d", "''")               # right double quote
    return s


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def gpio_notes(pin_table: dict, gpio: int) -> str:
    entry = pin_table.get(str(gpio))
    if entry:
        return latex_escape(entry["notes"])
    return ""


def interface_label(comp: dict, catalog: dict) -> str:
    iface = catalog.get("interface", "—")
    if iface == "i2c":
        addr = comp.get("i2c_address")
        if addr:
            return latex_escape(f"I2C 0x{addr:02X}")
        return "I2C"
    if iface == "spi":
        return "SPI"
    if iface == "adc":
        return "ADC"
    if iface == "onewire":
        return "1-Wire"
    if iface == "gpio":
        return "GPIO"
    return latex_escape(iface)


def gpio_summary(comp: dict) -> str:
    parts = [f"{latex_escape(pin)}={latex_escape(str(gpio))}"
             for pin, gpio in comp.get("pin_mapping", {}).items()]
    return ", ".join(parts)


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate(project_path: Path, output_path: Path) -> None:
    project   = load_json(project_path)
    pin_table = load_json(PIN_TABLE)

    # Load all catalog entries referenced by the project
    catalogs = {}
    for comp in project["components"]:
        cid = comp["catalog_id"]
        catalogs[cid] = load_json(CATALOG_DIR / f"{cid}.json")

    demo_name    = project_path.parent.name          # e.g. "smart_farm_node"
    project_name = demo_name.replace("_", " ").title()
    gen_date     = date.today().isoformat()
    buses        = project.get("buses", {})
    screen       = project.get("screen")

    lines = []

    # ------------------------------------------------------------------
    # Preamble
    # ------------------------------------------------------------------
    lines += [
        r"\documentclass[a4paper,11pt]{article}",
        r"\usepackage[a4paper,margin=2.5cm]{geometry}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage{textcomp}",
        r"\usepackage{graphicx}",
        r"\usepackage{booktabs}",
        r"\usepackage{longtable}",
        r"\usepackage{tikz}",
        r"\usetikzlibrary{shapes.geometric,arrows.meta,positioning,fit,backgrounds}",
        r"\usepackage{listings}",
        r"\usepackage{xcolor}",
        r"\usepackage[hidelinks]{hyperref}",
        r"\usepackage{caption}",
        r"\usepackage{parskip}",
        "",
        r"\definecolor{pinpilotblue}{RGB}{30,100,200}",
        r"\definecolor{espcol}{RGB}{220,235,255}",
        r"\definecolor{sensorcol}{RGB}{220,255,220}",
        r"\definecolor{actuatorcol}{RGB}{255,235,200}",
        r"\definecolor{displaycol}{RGB}{255,220,255}",
        "",
        r"\hypersetup{colorlinks=false}",
        "",
        r"\title{\textbf{\color{pinpilotblue}PinPilot Wiring Documentation}\\[0.5em]"
        rf"\large {latex_escape(project_name)}\\[0.3em]"
        r"\normalsize Board: ESP32 DevKit (WROOM-32)}",
        r"\author{Generated by \textbf{PinPilot} (IBM Bob 2.0 Hackathon)}",
        r"\date{\today}",
        "",
    ]

    # ------------------------------------------------------------------
    # Document begin + title
    # ------------------------------------------------------------------
    lines += [
        r"\begin{document}",
        r"\maketitle",
        r"\tableofcontents",
        r"\newpage",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 1 — Summary
    # ------------------------------------------------------------------
    lines += [
        r"\section{Project Summary}",
        "",
        rf"This document describes the wiring, pin assignment, bus configuration, and "
        rf"LVGL dashboard layout for the \textbf{{{latex_escape(project_name)}}} demo "
        rf"project. The target board is the \textbf{{ESP32 DevKit (WROOM-32)}}.",
        "",
        r"\begin{center}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Property} & \textbf{Value} \\",
        r"\midrule",
        rf"Board & ESP32 DevKit (WROOM-32) \\",
        rf"Components & {len(project['components'])} \\",
        rf"Buses & {', '.join(latex_escape(b) for b in buses)} \\",
        "WiFi enabled & " + ("Yes" if project.get("app", {}).get("wifi") else "No") + r" \\",
        "Serial logging & " + ("Yes" if project.get("app", {}).get("serial_logging") else "No") + r" \\",
        r"LVGL version & 9.2.2 \\",
        r"RAM usage & 29.0\% \\",
        r"Flash usage & 41.2\% \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 2 — Block diagram (TikZ)
    # ------------------------------------------------------------------
    lines += [
        r"\section{Block Diagram}",
        "",
        r"\begin{center}",
        r"\begin{tikzpicture}[",
        r"  node distance=0.6cm and 1.8cm,",
        r"  every node/.style={font=\small},",
        r"  box/.style={draw, rounded corners=3pt, minimum width=2.8cm, minimum height=0.9cm, align=center},",
        r"  esp/.style={box, fill=espcol, draw=pinpilotblue, thick, minimum width=3.4cm},",
        r"  sensor/.style={box, fill=sensorcol},",
        r"  actuator/.style={box, fill=actuatorcol},",
        r"  display/.style={box, fill=displaycol},",
        r"  arr/.style={-{Stealth}, thick},",
        r"  barr/.style={{Stealth}-{Stealth}, thick},",
        r"]",
        r"  % ESP32 centre",
        r"  \node[esp] (esp) {ESP32\\DevKit};",
        r"  % Sensors — left column",
        r"  \node[sensor, left=of esp, yshift=2.0cm] (soil) {soil\_1\\Soil Sensor};",
        r"  \node[sensor, left=of esp, yshift=0.6cm] (ds)   {ds18b20\_1\\DS18B20};",
        r"  \node[sensor, left=of esp, yshift=-0.8cm] (bme)  {bme280\_1\\BME280};",
        r"  % Actuator — right top",
        r"  \node[actuator, right=of esp, yshift=1.0cm] (relay) {relay\_1\\Relay};",
        r"  % Display — right bottom",
        r"  \node[display, right=of esp, yshift=-1.0cm] (tft) {ili9341\_1\\ILI9341 TFT};",
        r"  % Arrows",
        r"  \draw[arr] (soil.east)  -- node[above,font=\tiny]{ADC GPIO34}  (esp.west |- soil.east);",
        r"  \draw[arr] (ds.east)    -- node[above,font=\tiny]{1-Wire GPIO4} (esp.west |- ds.east);",
        r"  \draw[barr] (bme.east)  -- node[above,font=\tiny]{I2C GPIO21/22} (esp.west |- bme.east);",
        r"  \draw[arr] (esp.east |- relay.west) -- node[above,font=\tiny]{GPIO26} (relay.west);",
        r"  \draw[barr] (esp.east |- tft.west)  -- node[above,font=\tiny]{SPI GPIO18/19/23} (tft.west);",
        r"\end{tikzpicture}",
        r"\end{center}",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 3 — Component list
    # ------------------------------------------------------------------
    lines += [
        r"\section{Component List}",
        "",
        r"\begin{longtable}{llll}",
        r"\toprule",
        r"\textbf{Instance ID} & \textbf{Catalog Name} & \textbf{Interface} & \textbf{GPIO Summary} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for comp in project["components"]:
        cid     = comp["catalog_id"]
        cat     = catalogs[cid]
        iid     = latex_escape(comp["instance_id"])
        cname   = latex_escape(cat["name"])
        iface   = interface_label(comp, cat)
        gsum    = gpio_summary(comp)
        lines.append(rf"{iid} & {cname} & {iface} & {gsum} \\")
    lines += [
        r"\end{longtable}",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 4 — Wiring table
    # ------------------------------------------------------------------
    lines += [
        r"\section{Wiring Table}",
        "",
        r"\begin{longtable}{p{2.5cm}p{2cm}p{1.5cm}p{7.5cm}}",
        r"\toprule",
        r"\textbf{Instance} & \textbf{Pin} & \textbf{GPIO} & \textbf{GPIO Notes} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for comp in project["components"]:
        iid = latex_escape(comp["instance_id"])
        for pin_name, gpio in comp.get("pin_mapping", {}).items():
            pname = latex_escape(pin_name)
            notes = gpio_notes(pin_table, gpio)
            lines.append(rf"{iid} & {pname} & {gpio} & {notes} \\")
        lines.append(r"\midrule")
    lines += [
        r"\end{longtable}",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 5 — Pin Map
    # ------------------------------------------------------------------
    lines += [
        r"\section{Pin Map}",
        "",
        r"All ESP32 GPIO assignments at a glance:",
        "",
        r"\begin{center}",
        r"\begin{tabular}{rll}",
        r"\toprule",
        r"\textbf{GPIO} & \textbf{Assigned To} & \textbf{Pin / Function} \\",
        r"\midrule",
    ]
    # Collect all gpio → (instance, pin_name) pairs, sorted by GPIO number
    assignments = []
    for comp in project["components"]:
        for pin_name, gpio in comp.get("pin_mapping", {}).items():
            assignments.append((gpio, comp["instance_id"], pin_name))
    assignments.sort()
    for gpio, iid, pin_name in assignments:
        lines.append(
            rf"{gpio} & {latex_escape(iid)} & {latex_escape(pin_name)} \\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 6 — Bus configuration
    # ------------------------------------------------------------------
    lines += [r"\section{Bus Configuration}", ""]

    if "i2c0" in buses:
        b = buses["i2c0"]
        lines += [
            r"\subsection{I2C (i2c0)}",
            r"\begin{tabular}{ll}",
            r"\toprule",
            r"\textbf{Parameter} & \textbf{Value} \\",
            r"\midrule",
            rf"SDA & GPIO {b['sda']} \\",
            rf"SCL & GPIO {b['scl']} \\",
            rf"Frequency & {b['frequency']//1000}\,kHz \\",
            r"\midrule",
        ]
        for comp in project["components"]:
            if comp.get("bus_id") == "i2c0":
                addr = comp.get("i2c_address", "—")
                lines.append(
                    rf"{latex_escape(comp['instance_id'])} address & "
                    rf"0x{addr:02X} ({addr}) \\"
                )
        lines += [r"\bottomrule", r"\end{tabular}", ""]

    if "spi0" in buses:
        b = buses["spi0"]
        lines += [
            r"\subsection{SPI (spi0)}",
            r"\begin{tabular}{ll}",
            r"\toprule",
            r"\textbf{Parameter} & \textbf{Value} \\",
            r"\midrule",
            rf"MOSI & GPIO {b['mosi']} \\",
            rf"MISO & GPIO {b['miso']} \\",
            rf"SCK  & GPIO {b['sck']} \\",
            rf"Frequency & {b['frequency']//1000000}\,MHz \\",
        ]
        for comp in project["components"]:
            if comp.get("bus_id") == "spi0":
                cs_gpio = comp.get("pin_mapping", {}).get("CS", "—")
                lines.append(
                    rf"CS ({latex_escape(comp['instance_id'])}) & GPIO {cs_gpio} \\"
                )
        lines += [r"\bottomrule", r"\end{tabular}", ""]

    # ------------------------------------------------------------------
    # Section 7 — Per-component notes
    # ------------------------------------------------------------------
    lines += [r"\section{Component Notes}", ""]
    for comp in project["components"]:
        cid   = comp["catalog_id"]
        cat   = catalogs[cid]
        notes = cat.get("notes", "").strip()
        if not notes:
            continue
        iid = latex_escape(comp["instance_id"])
        cname = latex_escape(cat["name"])
        lines += [
            rf"\subsection{{{iid} --- {cname}}}",
            "",
            latex_escape(notes),
            "",
        ]

    # ------------------------------------------------------------------
    # Section 8 — LVGL Dashboard layout (screen block)
    # ------------------------------------------------------------------
    if screen:
        widgets = screen.get("widgets", [])
        lines += [
            r"\section{LVGL Dashboard Layout}",
            "",
            rf"Driver: \texttt{{{latex_escape(screen.get('driver',''))}}}\quad "
            rf"Display instance: \texttt{{{latex_escape(screen.get('instance_id',''))}}}",
            "",
            r"Firmware built with \textbf{LVGL v9.2.2} (TFT\_eSPI back-end). "
            r"RAM usage: \textbf{29.0\%}, Flash usage: \textbf{41.2\%}.",
            "",
            r"\begin{longtable}{p{2.8cm}p{1.5cm}p{3.5cm}rrrrrr}",
            r"\toprule",
            r"\textbf{Widget ID} & \textbf{Type} & \textbf{Binding} & "
            r"\textbf{X} & \textbf{Y} & \textbf{W} & \textbf{H} & \textbf{Min} & \textbf{Max} \\",
            r"\midrule",
            r"\endhead",
            r"\bottomrule",
            r"\endfoot",
        ]
        for w in widgets:
            wid     = latex_escape(w.get("id", ""))
            wtype   = latex_escape(w.get("type", ""))
            binding = latex_escape(w.get("binding", ""))
            x       = str(w.get("x", ""))
            y       = str(w.get("y", ""))
            width   = str(w.get("width",  "—"))
            height  = str(w.get("height", "—"))
            wmin    = str(w.get("min", "—"))
            wmax    = str(w.get("max", "—"))
            lines.append(
                rf"{wid} & {wtype} & {binding} & {x} & {y} & {width} & {height} & {wmin} & {wmax} \\"
            )
        lines += [r"\end{longtable}", ""]

        # ASCII-art representation of the 320x240 canvas
        lines += [
            r"\subsection{Dashboard Canvas (320\texttimes240)}",
            "",
            r"\begin{center}",
            r"\begin{tikzpicture}[scale=0.022, every node/.style={font=\tiny}]",
            r"  % Screen border 320x240",
            r"  \draw[thick] (0,0) rectangle (320,240);",
            r"  \node at (160,232) {ILI9341 320\texttimes240};",
        ]
        # Draw each widget as a rectangle (y-flipped: tikz y=0 at bottom)
        for w in widgets:
            wx  = w.get("x", 0)
            wy  = 240 - w.get("y", 0) - w.get("height", 20)
            ww  = w.get("width",  80)
            wh  = w.get("height", 20)
            wid = w.get("id", "")
            wtype = w.get("type", "")
            # Only draw if it has width/height
            if "width" in w and "height" in w:
                fill = "sensorcol" if wtype == "arc" else ("displaycol" if wtype == "chart" else "espcol")
                lines.append(
                    rf"  \draw[fill={fill}!60] ({wx},{wy}) rectangle ({wx+ww},{wy+wh});"
                )
                cx = wx + ww / 2
                cy = wy + wh / 2
                lines.append(
                    rf"  \node[align=center] at ({cx},{cy}) {{{latex_escape(wid)}}};",
                )
            else:
                # value widgets — small box
                lines.append(
                    rf"  \draw[fill=espcol!60] ({wx},{wy-10}) rectangle ({wx+80},{wy+10});"
                )
                lines.append(
                    rf"  \node at ({wx+40},{wy}) {{{latex_escape(wid)}}};",
                )
        lines += [
            r"\end{tikzpicture}",
            r"\end{center}",
            "",
        ]

    # ------------------------------------------------------------------
    # Section 9 — Firmware build result
    # ------------------------------------------------------------------
    lines += [
        r"\section{Firmware Build Result}",
        "",
        r"\begin{center}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Item} & \textbf{Value} \\",
        r"\midrule",
        r"LVGL version & 9.2.2 \\",
        r"TFT\_eSPI version & 2.5.43 \\",
        r"Build status & \textcolor{green!60!black}{\textbf{SUCCESS}} \\",
        r"RAM usage & 29.0\% \\",
        r"Flash usage & 41.2\% \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        "",
    ]

    # ------------------------------------------------------------------
    # End document
    # ------------------------------------------------------------------
    lines += [r"\end{document}", ""]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[PinPilot] LaTeX written -> {output_path}")


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python scripts/generate_docs.py <project.json> <output.tex>")
        sys.exit(1)
    generate(Path(sys.argv[1]), Path(sys.argv[2]))
