"""
validate_project.py — PinPilot project file validator.
Generated by PinPilot. Source: docs/PROJECT_PINPILOT.md §8.
Usage: python scripts/validate_project.py <project.json>
Exit code: 0 = valid (no errors; warnings may be present), 1 = errors found, 2 = bad arguments/missing file.
"""

import argparse
import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (all relative to repository root)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).parent.parent
SCHEMA_DIR = REPO_ROOT / "schema"
CATALOG_DIR = REPO_ROOT / "catalog"

# ---------------------------------------------------------------------------
# Lazy import: jsonschema is a dependency declared in requirements.txt
# ---------------------------------------------------------------------------
try:
    import jsonschema
except ImportError:
    print("ERROR: jsonschema is not installed. Run: pip install jsonschema>=4.0", file=sys.stderr)
    sys.exit(2)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> dict:
    try:
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"ERROR: Cannot load {path}: {exc}", file=sys.stderr)
        sys.exit(2)


def load_catalog_component(catalog_id: str) -> dict | None:
    """Return the catalog entry for catalog_id, or None if not found."""
    entry_path = CATALOG_DIR / "components" / f"{catalog_id}.json"
    if not entry_path.exists():
        return None
    return load_json(entry_path)


def load_pin_table() -> dict:
    return load_json(CATALOG_DIR / "esp32_devkit_pins.json")


FLASH_PINS = set(range(6, 12))          # GPIO6–11
INPUT_ONLY_PINS = {34, 35, 36, 39}     # GPIO37/38 not broken out on WROOM-32/DevKit
STRAPPING_PINS = {0, 2, 5, 12, 15}
UART0_PINS = {1, 3}
# GPIO37 and GPIO38 exist on the die but are NOT broken out on WROOM-32/DevKit boards.
EXISTING_GPIOS = set(range(0, 20)) | {21, 22, 23} | set(range(25, 28)) | {32, 33, 34, 35, 36, 39}


# ---------------------------------------------------------------------------
# Stage 1: JSON Schema validation
# ---------------------------------------------------------------------------

def validate_schema(project: dict) -> list[str]:
    """Return a list of schema-level error messages (empty = OK)."""
    schema_path = SCHEMA_DIR / "project.schema.json"
    schema = load_json(schema_path)
    validator = jsonschema.Draft7Validator(schema)
    errors = []
    for err in sorted(validator.iter_errors(project), key=lambda e: list(e.path)):
        path = " > ".join(str(p) for p in err.path) or "(root)"
        errors.append(f"Schema error at {path}: {err.message}")
    return errors


# ---------------------------------------------------------------------------
# Stage 2: Semantic / ESP32-specific validation  (§8)
# ---------------------------------------------------------------------------

def _pin_role_map(catalog_entry: dict) -> dict[str, str]:
    """
    Return {pin_name_upper: role} for all pins in the catalog entry.
    pin names are upper-cased for case-insensitive lookup.
    """
    return {
        p["name"].upper(): p["role"]
        for p in catalog_entry.get("pins", [])
    }


def collect_all_gpio_assignments(project: dict) -> dict[int, list[str]]:
    """
    Return a mapping of gpio_number -> list of (instance_id, pin_name) strings.
    Also covers bus pins.
    """
    assignments: dict[int, list[str]] = {}

    def assign(gpio: int, label: str) -> None:
        assignments.setdefault(gpio, []).append(label)

    # Component pin_mapping — keyed by component pin name (e.g. "CS", "SDA")
    for comp in project.get("components", []):
        iid = comp["instance_id"]
        for pin_name, gpio in comp.get("pin_mapping", {}).items():
            assign(gpio, f"{iid}.{pin_name}")

    # Bus pins (may overlap with component pin_mapping for shared buses — that is expected)
    buses = project.get("buses", {})
    for bus_id, bus_cfg in buses.items():
        for pin_role, gpio in bus_cfg.items():
            if pin_role == "frequency":
                continue
            assign(gpio, f"bus:{bus_id}.{pin_role}")

    return assignments


def validate_semantics(project: dict, pin_table: dict) -> tuple[list[str], list[str]]:
    """
    Return (errors, warnings) lists.
    All rule references are to docs/PROJECT_PINPILOT.md §8.

    pin_mapping keys are component pin names (e.g. "CS", "SDA", "DC", "RESET").
    Role-based checks resolve the role from the catalog pin list by name.
    """
    errors: list[str] = []
    warnings: list[str] = []
    wifi_enabled: bool = project.get("app", {}).get("wifi", False)

    # -----------------------------------------------------------------------
    # Build a flat list of every GPIO assignment in the project
    # (component pin_mappings only — not bus pins, since shared bus pins are
    # legitimately reused by multiple components)
    # -----------------------------------------------------------------------
    component_gpio_assignments: dict[int, list[str]] = {}

    def comp_assign(gpio: int, label: str) -> None:
        component_gpio_assignments.setdefault(gpio, []).append(label)

    for comp in project.get("components", []):
        iid = comp["instance_id"]
        for pin_name, gpio in comp.get("pin_mapping", {}).items():
            comp_assign(gpio, f"{iid}.{pin_name}")

    # -----------------------------------------------------------------------
    # Rule: GPIO must exist on this chip
    # -----------------------------------------------------------------------
    all_referenced_gpios: set[int] = set()
    for comp in project.get("components", []):
        all_referenced_gpios.update(comp.get("pin_mapping", {}).values())
    buses = project.get("buses", {})
    for bus_cfg in buses.values():
        for k, v in bus_cfg.items():
            if k != "frequency":
                all_referenced_gpios.add(v)

    for gpio in sorted(all_referenced_gpios):
        if gpio not in EXISTING_GPIOS:
            errors.append(
                f"GPIO{gpio} does not exist on ESP32-WROOM-32 or is not broken out on this DevKit. "
                f"Valid GPIOs: 0-19, 21-23, 25-27, 32-36, 39."
            )

    # -----------------------------------------------------------------------
    # Rule §8 E1: Flash pins GPIO6–11 must not be used
    # -----------------------------------------------------------------------
    for gpio in sorted(all_referenced_gpios & FLASH_PINS):
        errors.append(
            f"GPIO{gpio} is connected to the internal SPI flash and must not be used. "
            f"Affected assignments: {component_gpio_assignments.get(gpio, ['bus pin'])}."
        )

    # -----------------------------------------------------------------------
    # Rule §8 E2: Output function on input-only pins GPIO34–39
    # Pin_mapping is keyed by component pin name; resolve role from catalog.
    # -----------------------------------------------------------------------
    OUTPUT_ROLES = {
        "gpio_out", "spi_mosi", "spi_sck", "spi_cs",
        "i2c_sda", "i2c_scl", "uart_tx", "pwm",
        "onewire",  # 1-Wire is bidirectional but needs drive capability
    }
    for comp in project.get("components", []):
        iid = comp["instance_id"]
        catalog_entry = load_catalog_component(comp["catalog_id"])
        role_map = _pin_role_map(catalog_entry) if catalog_entry else {}
        for pin_name, gpio in comp.get("pin_mapping", {}).items():
            if gpio in INPUT_ONLY_PINS:
                role = role_map.get(pin_name.upper(), "")
                if role in OUTPUT_ROLES:
                    errors.append(
                        f"{iid}.{pin_name} (role: {role}) is assigned to GPIO{gpio} which is input-only "
                        f"(GPIO34, 35, 36, 39 have no output capability and no internal pull-ups)."
                    )

    # -----------------------------------------------------------------------
    # Rule §8 E3: Two I2C devices with the same address on the same bus
    # -----------------------------------------------------------------------
    i2c_bus_addresses: dict[str, dict[int, str]] = {}
    for comp in project.get("components", []):
        iid = comp["instance_id"]
        catalog_entry = load_catalog_component(comp["catalog_id"])
        if catalog_entry is None:
            # Unknown catalog entry — skip (schema validator should catch catalog_id issues)
            continue
        if catalog_entry.get("interface") != "i2c":
            continue
        bus_id = comp.get("bus_id", "i2c0")
        addr = comp.get("i2c_address")
        if addr is None:
            # Use catalog default
            addr = catalog_entry.get("i2c_addresses", {}).get("default")
        if addr is None:
            continue
        if bus_id not in i2c_bus_addresses:
            i2c_bus_addresses[bus_id] = {}
        if addr in i2c_bus_addresses[bus_id]:
            other_iid = i2c_bus_addresses[bus_id][addr]
            # Build suggestion from alternatives
            alternatives = catalog_entry.get("i2c_addresses", {}).get("alternatives", [])
            alt_hint = ""
            if alternatives:
                alts = ", ".join(f"0x{a['address']:02X} ({a['how']})" for a in alternatives)
                alt_hint = f" Alternative address(es): {alts}."
            errors.append(
                f"I2C address conflict on {bus_id}: both '{iid}' and '{other_iid}' "
                f"use address 0x{addr:02X}.{alt_hint}"
            )
        else:
            i2c_bus_addresses[bus_id][addr] = iid

    # -----------------------------------------------------------------------
    # Rule §8 E4: Same GPIO assigned to two different functions via component pin_mapping
    # (Bus pins are excluded from duplicate checks — shared bus lines are expected)
    # -----------------------------------------------------------------------
    bus_gpios: set[int] = set()
    for bus_cfg in buses.values():
        for k, v in bus_cfg.items():
            if k != "frequency":
                bus_gpios.add(v)

    for gpio, labels in component_gpio_assignments.items():
        if gpio in bus_gpios:
            continue  # pin is a bus pin, skip duplicate check
        if len(labels) > 1:
            errors.append(
                f"GPIO{gpio} is assigned to multiple functions: {labels}. "
                f"Each GPIO may only serve one function."
            )

    # -----------------------------------------------------------------------
    # Rule §8 E5: ADC2 pin used for analog sensor while WiFi is enabled
    # Resolve pin role from catalog; flag pins with role "adc" on ADC2 GPIOs.
    # -----------------------------------------------------------------------
    if wifi_enabled:
        for comp in project.get("components", []):
            iid = comp["instance_id"]
            catalog_entry = load_catalog_component(comp["catalog_id"])
            if catalog_entry is None:
                continue
            if catalog_entry.get("interface") != "adc":
                continue
            role_map = _pin_role_map(catalog_entry)
            for pin_name, gpio in comp.get("pin_mapping", {}).items():
                role = role_map.get(pin_name.upper(), "")
                if role == "adc":
                    gpio_info = pin_table.get(str(gpio), {})
                    if gpio_info.get("adc2", False):
                        errors.append(
                            f"{iid} uses GPIO{gpio} (ADC2 channel) for an analog reading, "
                            f"but WiFi is enabled. ADC2 is disabled by the WiFi driver. "
                            f"Move the sensor to an ADC1 pin (GPIO32-36, 39)."
                        )

    # -----------------------------------------------------------------------
    # Rule §8 W1: Strapping pins in use
    # -----------------------------------------------------------------------
    used_strapping = sorted(all_referenced_gpios & STRAPPING_PINS)
    for gpio in used_strapping:
        extra = ""
        if gpio == 12:
            extra = " WARNING: GPIO12 pulled HIGH at boot breaks flash voltage selection on most DevKits."
        warnings.append(
            f"GPIO{gpio} is a strapping pin (affects boot behavior).{extra} "
            f"Verify it is at the correct level at power-on."
        )

    # -----------------------------------------------------------------------
    # Rule §8 W2: UART0 pins in use
    # -----------------------------------------------------------------------
    used_uart0 = sorted(all_referenced_gpios & UART0_PINS)
    for gpio in used_uart0:
        name = "TX" if gpio == 1 else "RX"
        warnings.append(
            f"GPIO{gpio} (UART0 {name}) is used, but it is also the USB serial port. "
            f"This conflicts with serial logging when the board is connected via USB."
        )

    # -----------------------------------------------------------------------
    # Rule §8 W3: 5V logic component connected directly
    # -----------------------------------------------------------------------
    for comp in project.get("components", []):
        iid = comp["instance_id"]
        catalog_entry = load_catalog_component(comp["catalog_id"])
        if catalog_entry is None:
            continue
        logic_v = catalog_entry.get("logic_voltage", 3.3)
        if logic_v > 3.3:
            warnings.append(
                f"{iid} ({comp['catalog_id']}) has {logic_v}V logic levels. "
                f"Connecting it directly to the ESP32 (3.3V) may damage the MCU. "
                f"Use a level shifter or voltage divider on signal lines."
            )

    return errors, warnings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate a PinPilot project.json file against the schema and ESP32 rules."
    )
    parser.add_argument("project_file", type=Path, help="Path to the project.json file to validate.")
    args = parser.parse_args()

    project_path: Path = args.project_file
    if not project_path.exists():
        print(f"ERROR: File not found: {project_path}", file=sys.stderr)
        sys.exit(2)

    project = load_json(project_path)
    pin_table = load_pin_table()

    print(f"Validating: {project_path}")
    print()

    # Stage 1: schema
    schema_errors = validate_schema(project)
    if schema_errors:
        for msg in schema_errors:
            print(f"  [SCHEMA ERROR] {msg}")
        print()
        print(f"Schema validation failed with {len(schema_errors)} error(s). Semantic checks skipped.")
        sys.exit(1)

    print("  [OK] Schema validation passed.")
    print()

    # Stage 2: semantics
    errors, warnings = validate_semantics(project, pin_table)

    for msg in warnings:
        print(f"  [WARNING] {msg}")
    for msg in errors:
        print(f"  [ERROR]   {msg}")

    print()
    if errors:
        print(f"Validation FAILED: {len(errors)} error(s), {len(warnings)} warning(s).")
        sys.exit(1)
    else:
        print(f"Validation PASSED: 0 errors, {len(warnings)} warning(s).")
        sys.exit(0)


if __name__ == "__main__":
    main()
