// Generated by PinPilot. Source: project.json
// Purpose: Arduino main entry point for weather_station firmware.
// Do not edit manually — regenerate from project.json.

#include <Arduino.h>
#include <Wire.h>

#include "pinmap.h"
#include "components/bme280_1.h"
#include "components/bh1750_1.h"
#include "components/display.h"

// ── Global component instances (defined in their respective .cpp files) ───
// bme280_1  — extern BME280_1 bme280_1
// bh1750_1  — extern BH1750_1 bh1750_1
Display display;

// ── Display refresh interval ──────────────────────────────────────────────
static const uint32_t DISPLAY_INTERVAL_MS = 500;
static uint32_t lastDisplayUpdate = 0;

void setup() {
    Serial.begin(115200);
    delay(200);  // allow Serial to settle (setup() only — not in loop())

    // ── Startup banner ────────────────────────────────────────────────────
    Serial.println("============================================");
    Serial.println("  PinPilot Firmware — weather_station");
    Serial.println("  Source: project.json");
    Serial.println("============================================");
    Serial.printf("  I2C bus  : SDA=GPIO%d  SCL=GPIO%d  freq=%d Hz\n",
                  I2C_SDA, I2C_SCL, I2C_FREQ);
    Serial.printf("  ADDR_BME280_1  = 0x%02X\n", ADDR_BME280_1);
    Serial.printf("  ADDR_BH1750_1  = 0x%02X\n", ADDR_BH1750_1);
    Serial.printf("  ADDR_SSD1306_1 = 0x%02X\n", ADDR_SSD1306_1);
    Serial.println("--------------------------------------------");

    // ── Shared I2C bus (one Wire.begin — before any device begin()) ───────
    Wire.begin(I2C_SDA, I2C_SCL);
    Wire.setClock(I2C_FREQ);

    // ── Device initialisation ─────────────────────────────────────────────
    Serial.print("  bme280_1  : ");
    Serial.println(bme280_1.begin() ? "OK" : "NOT FOUND");

    Serial.print("  bh1750_1  : ");
    Serial.println(bh1750_1.begin() ? "OK" : "NOT FOUND");

    Serial.print("  display   : ");
    Serial.println(display.begin() ? "OK" : "NOT FOUND");

    Serial.println("============================================");
    Serial.println("  Setup complete. Entering main loop.");
    Serial.println("============================================");
}

void loop() {
    // ── Non-blocking sensor updates ───────────────────────────────────────
    bme280_1.update();
    bh1750_1.update();

    // ── Refresh display at DISPLAY_INTERVAL_MS ────────────────────────────
    if (millis() - lastDisplayUpdate >= DISPLAY_INTERVAL_MS) {
        lastDisplayUpdate = millis();
        display.update(
            bme280_1.getTemperature(),
            bme280_1.getHumidity(),
            bh1750_1.getLight()
        );
    }
}
