// Generated by PinPilot. Source: project.json
// Purpose: GPIO pin assignments and I2C addresses for weather_station firmware.
// Do not edit manually — regenerate from project.json.

#pragma once

// ── I2C bus (i2c0) ────────────────────────────────────────────────────────
#define I2C_SDA          21
#define I2C_SCL          22
#define I2C_FREQ         400000    // Hz

// ── I2C device addresses ──────────────────────────────────────────────────
#define ADDR_BME280_1    0x76      // decimal 118 — SDO tied to GND
#define ADDR_BH1750_1    0x23      // decimal  35 — ADDR tied to GND
#define ADDR_SSD1306_1   0x3C      // decimal  60 — default

// ── Pin map summary ───────────────────────────────────────────────────────
// GPIO 21  — I2C SDA (shared bus: bme280_1, bh1750_1, ssd1306_1)
// GPIO 22  — I2C SCL (shared bus: bme280_1, bh1750_1, ssd1306_1)
